import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * User 테이블 생성
 */
export class AutoGenerated1739447107963 implements MigrationInterface {
  name = "AutoGenerated1739447107963";

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(32) NOT NULL, \`name\` varchar(32) NOT NULL, UNIQUE INDEX \`IDX_2e5b50f4b7c081eceea476ad12\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `DROP INDEX \`IDX_2e5b50f4b7c081eceea476ad12\` ON \`users\``,
    );
    await queryRunner.query(`DROP TABLE \`users\``);
  }
}
