name: Trivy security scan

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  trivy-security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Scan @nettiwork
        uses: aquasecurity/trivy-action@0.28.0
        with:
          exit-code: 1
          scan-type: "fs"
          scan-ref: "./@nettiwork"
          severity: "CRITICAL,HIGH"
      
      - name: Scan api-server
        uses: aquasecurity/trivy-action@0.28.0
        with:
          exit-code: 1
          scan-type: "fs"
          scan-ref: "./api-server"
          severity: "CRITICAL,HIGH"
